import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Menu } from "lucide-react";
import { SidebarContent } from "@/components/Sidebar";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Navbar } from "@/components/Navbar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-TW">
      <body>
        <div className="flex h-screen overflow-hidden">
          {/* --- 桌機版側邊欄 --- */}
          {/* hidden: 手機預設隱藏; md:flex: 平板/電腦以上顯示為 Flex */}
          <aside className="hidden md:flex w-64 flex-col border-r shadow-sm">
            <SidebarContent />
          </aside>

          <div className="flex flex-col flex-1 w-full overflow-hidden">
            {/* --- 手機版頂部 Header --- */}
            {/* md:hidden: 電腦版隱藏 */}
           <Navbar/>

            {/* --- 主要內容呈現區 --- */}
            <main className="flex-1 overflow-y-auto bg-white p-6">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
